### ISSUE TITLE
Exception AttributeError running the code on a PowerPDU 4C

### ISSUE THREAD

**Issue by Rocco83** [tomsajan/netio-exporter#2]
Hi,

Thanks for the code.

I was trying to play around it, but i see an exception coming through.
I've tried with both a debian bullseye (no pip, taken the packages from the repo) & docker image.

See the output from the latter.
Trying to dig around, but in the meantine...

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 45, in prometheus_app
    output = encoder(r)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 25, in generate_latest
    ['{0}="{1}"'.format(
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 26, in <listcomp>
    k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"'))
AttributeError: ("'NoneType' object has no attribute 'replace'", Metric(netio_agent, Global info about Netio agent, info, , [Sample(name='netio_agent_info', labels={'model': 'PowerPDU 4C', 'version': '3.4.2', 'json_version': '2.1', 'name': 'pdunetio1', 'outputs': '4', 'sn': None, 'target': 'http://<MYIP>/netio.json'}, value=1, timestamp=None, exemplar=None)]))
<MYIP> - - [03/Feb/2022 04:42:52] "GET /metrics HTTP/1.1" 500 59
```

**Comment by Rocco83** [comment]
I've found the issue.

For some reason, this is the portion of my json output:
```
	"Agent":	{
		"Model":	"PowerPDU 4C",
		"Version":	"3.4.2",
		"JSONVer":	"2.1",
		"DeviceName":	"pdunetio1",
		"VendorID":	0,
		"OemID":	0,
		"SerialNumber":	"",
		"Uptime":	150303,
		"Time":	"2022-02-03T05:54:25+01:00",
		"NumOutputs":	4
	},
```

As you can see, SerialNumber is null.
The mac address is not present as well.
This is leading to the error seen.
I'm going to push a PR with the fix (and a further debug line)

**Comment by tomsajan** [comment]
Hi @Rocco83 , thank you very much for your interest in this exporter :).
I find it quire puzzling that your 4C doesn't have the `SerialNumber` field filled in. I tried to update mine to the latest version I found (3.4.0), but the ugprade failed, so I cannot verify this. My netio reports its `SerialNumber` just fine.
However I tried to simulate it and it indeed crashed the way you reported. 
Thanks for taking the initiative and submitting the fix. I just added a few comments and it will be fine :)

Have a nice day :)

BTW you could try to contact Netio to get to the bottom of this issue.

**Comment by tomsajan** [comment]
Thanks for your suggestion and code :)
