### ISSUE TITLE
ARM docker support

### ISSUE THREAD

**Issue by imclint21** [tomsajan/netio-exporter#8]
Hi,

Would you mind release a docker image for ARM support?

Regards

**Comment by tomsajan** [comment]
Hi :)
Thank you for this suggestion. I will take a look on it :). I will get back to you :)

**Comment by tomsajan** [comment]
Hi @imclint21 so I pushed a new 0.0.5 image which is now a multiplatform build with arm support. 
Please let me know if it works for you :)

Thank you. 
Jan

**Comment by imclint21** [comment]
Awesome I'll try it!
